name: Go Test

on: 
  push:
    branches:
      - main  # mainブランチにプッシュされたときにテストを実行します
  pull_request:
    branches:
      - main  # mainブランチへのプルリクエストが作成されたときにテストを実行します

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
        db:
          image: postgres:13
          env:
            POSTGRES_PASSWORD: password
          ports:
            - 5432:5432
        redis:
          image: redis
          ports:
            - 6379:6379

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3

        - name: Wait for services
          run: |
            chmod +x ./wait-for-it.sh
            ./wait-for-it.sh localhost:5432 --timeout=15
            ./wait-for-it.sh localhost:6379 --timeout=15

        - name: Test
          run: go test -v ./api/...